package uk.ac.anglia.student.hilda.studentadviser.model;

/**
 * Created by Ibok on 07/04/2017.
 */

public class Answer {


    // An autogenerated id (unique for each user in the db

    private String key;
    private String r_when;
    private String r_how;
    private String r_where;
    private String r_how_much;
    private String r_who;
    private String r_links;
    private String r_what;

    public Answer() { }

    public Answer(String key) {
        this.key = key;
    }


    // Public methods
    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getR_when() {
        return r_when;
    }

    public void setR_when(String r_when) {
        this.r_when = r_when;
    }

    public String getR_how() {
        return r_how;
    }

    public void setR_how(String r_how) {
        this.r_how = r_how;
    }

    public String getR_where() {
        return r_where;
    }

    public void setR_where(String r_where) {
        this.r_where = r_where;
    }

    public String getR_how_much() {
        return r_how_much;
    }

    public void setR_how_much(String r_how_much) {
        this.r_how_much = r_how_much;
    }

    public String getR_who() {
        return r_who;
    }

    public void setR_who(String r_who) {
        this.r_who = r_who;
    }

    public String getR_links() {
        return r_links;
    }

    public void setR_links(String r_links) {
        this.r_links = r_links;
    }

    public String getR_what() {
        return r_what;
    }

    public void setR_what(String r_what) {
        this.r_what = r_what;
    }

    public String toString(){
        return "key = "+ this.key +"how = "+ this.r_how+"howmuch = "+ this.r_how_much +"links = "+ this.r_links +"what = "+ this.r_what +"when = "+ this.r_when +"where = "+ this.r_where +"who = "+ this.r_who;

    }

    public String getByContext(String context){
        String response = "";
        switch (context) {

            case "howmuch":
                response = getR_how_much();
                break;

            case "how":
                response = getR_how();
                break;

            case "what":
                response = getR_what();
                break;

            case "when":
                response = getR_when();
                break;
            case "where":
                response = getR_where();
                break;
            case "who":
                response = getR_how();
                break;
        }
        return response;
    }


}
